### ISSUE TITLE
Idea: maybe a better auto-update

### ISSUE THREAD

**Issue by hchiam** [marko-polo-cheno/Habit-Tracker-Extension#3]
Store last update date and compare it with today's date? 
I'm wondering if the 3am setTimeout will actually do what we expect.

**Comment by hchiam** [comment]
https://github.com/marko-polo-cheno/Habit-Tracker-Extension/blob/master/brain.js#L22 
and surrounding lines should be inside the get 
https://github.com/marko-polo-cheno/Habit-Tracker-Extension/blob/master/brain.js#L16
because of the timing issue (lastDate will always be null inside the if statement).

Make sure you test that it works the way you expect.

**Comment by marko-polo-cheno** [comment]
Oh lol yes. I was coding outside because I messed up the brackets for the get function, so I coded outside of the error, fixed the error afterwards, but didn’t put the code where it should have been. Thanks!! I’ll fix that soon.

Mark

**Comment by hchiam** [comment]
Nice! https://github.com/marko-polo-cheno/Habit-Tracker-Extension/compare/v2.5...3 

Also, remember to test that it works the way you expect. 
I'll try doing some manual triggering but the final test will be waiting an actual day without opening the extension until the next day.

**Comment by hchiam** [comment]
I think I found a fix: https://github.com/marko-polo-cheno/Habit-Tracker-Extension/pull/4 
You can test it without waiting for a day: 
1) under [line 23](https://github.com/marko-polo-cheno/Habit-Tracker-Extension/pull/4/files#diff-57f9aef8872ec4ac70149e02a0eb94b4R23), add this: `lastDate --;`
2) at [line 151](https://github.com/marko-polo-cheno/Habit-Tracker-Extension/pull/4/files#diff-57f9aef8872ec4ac70149e02a0eb94b4R151), change `'date': new Date().getDate()` to `'date': lastDate`
3) the popup should update every time you click on the icon (as if it's a new day)

**Comment by marko-polo-cheno** [comment]
Hi Howard,

Am I supposed to click “merge pull request”? That’s the button that applies your changes, right?

Thanks,
Mark

**Comment by hchiam** [comment]
Yup! Thanks.
